//! `jev completions` — shell completion scripts.
//!
//! Generated by `clap_complete` from the same command definition the parser uses, so a
//! new flag is completable the moment it exists and a renamed one cannot leave a stale
//! completion behind.
//!
//! The script is written to stdout and nothing is installed: where completions belong
//! differs by shell and by distribution, and writing into a user's shell configuration
//! uninvited is not something a CLI should do.

use clap::CommandFactory as _;

use crate::cli::{Cli, CompletionsArgs};
use crate::commands::Session;
use crate::errors::Result;
use crate::exit;
use crate::render::json as render_json;

/// Runs `jev completions`.
pub(crate) fn run(session: &mut Session<'_>, args: &CompletionsArgs) -> Result<u8> {
    let mut command = Cli::command();
    let mut buffer = Vec::new();
    clap_complete::generate(args.shell, &mut command, "jev", &mut buffer);
    render_json::write_all(session.out, &buffer)?;

    session.note(&format!(
        "completion script for {}; see the README for where to install it",
        args.shell
    ));
    Ok(exit::SUCCESS)
}
